import { 
  FileJson, 
  Key, 
  Type, 
  Hash, 
  QrCode, 
  Clock, 
  Ruler, 
  Activity, 
  Palette, 
  Database,
  FileText,
  Link2,
  ImagePlay,
  Files,
  FileDown,
  FileDiff,
  Minimize2,
  BarChart2
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export interface Tool {
  id: string;
  name: string;
  description: string;
  category: string;
  path: string;
  icon: LucideIcon;
}

export const tools: Tool[] = [
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and minify JSON data instantly with deep tree view.',
    category: 'Data',
    path: '/json-formatter',
    icon: FileJson,
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure, complex passwords locally with strength indicator.',
    category: 'Security',
    path: '/password-generator',
    icon: Key,
  },
  {
    id: 'text-to-slug',
    name: 'Text to Slug',
    description: 'Convert any string into a URL-friendly slug.',
    category: 'String',
    path: '/text-to-slug',
    icon: Type,
  },
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder/Decoder',
    description: 'Instantly encode or decode Base64 strings safely inside your browser.',
    category: 'Data',
    path: '/base64-encoder',
    icon: Hash,
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Create and download customizable QR codes for links or text.',
    category: 'Media',
    path: '/qr-generator',
    icon: QrCode,
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps to human-readable dates and vice versa.',
    category: 'Time',
    path: '/timestamp-converter',
    icon: Clock,
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Quickly convert between different units (e.g., kg to block/pound).',
    category: 'Math',
    path: '/unit-converter',
    icon: Ruler,
  },
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate your Body Mass Index based on height and weight.',
    category: 'Health',
    path: '/bmi-calculator',
    icon: Activity,
  },
  {
    id: 'color-palette',
    name: 'Color Palette',
    description: 'Generate beautiful, harmonic color palettes for your next UI.',
    category: 'Design',
    path: '/color-palette',
    icon: Palette,
  },
  {
    id: 'random-data',
    name: 'Random Data Generator',
    description: 'Generate mock user data like names, emails, UUIDs instantly.',
    category: 'Data',
    path: '/random-data',
    icon: Database,
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Instantly generate MD5, SHA-1, and SHA-256 hashes online.',
    category: 'Security',
    path: '/hash-generator',
    icon: Hash,
  },
  {
    id: 'text-case-converter',
    name: 'Text Case Converter',
    description: 'Change text to UPPERCASE, lowercase, camelCase, snake_case.',
    category: 'String',
    path: '/text-case-converter',
    icon: Type,
  },
  {
    id: 'word-counter',
    name: 'Word & Character Counter',
    description: 'Count words, characters, sentences, and paragraphs instantly.',
    category: 'Writing',
    path: '/word-counter',
    icon: FileText,
  },
  {
    id: 'tinyurl-generator',
    name: 'TinyURL Generator',
    description: 'Generate short, readable URLs for long links instantly within your browser.',
    category: 'Network',
    path: '/tinyurl-generator',
    icon: Link2,
  },
  {
    id: 'image-to-gif',
    name: 'Images to GIF Converter',
    description: 'Convert multiple images into an animated GIF on the client side.',
    category: 'Media',
    path: '/image-to-gif',
    icon: ImagePlay,
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF Online',
    description: 'Combine multiple PDF documents into one single PDF securely.',
    category: 'Document',
    path: '/merge-pdf',
    icon: Files,
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF Converter',
    description: 'Convert .doc and .docx files to PDF instantly and securely.',
    category: 'Document',
    path: '/word-to-pdf',
    icon: FileDown,
  },
  {
    id: 'diff-checker',
    name: 'Diff Checker',
    description: 'Compare text and JSON differences with side-by-side or inline view.',
    category: 'Developer',
    path: '/diff-checker',
    icon: FileDiff,
  },
  {
    id: 'compression-tool',
    name: 'Compression Tool',
    description: 'Gzip compress and decompress text or JSON payloads instantly.',
    category: 'Data',
    path: '/compression-tool',
    icon: Minimize2,
  },
  {
    id: 'data-visualizer',
    name: 'Data Visualizer',
    description: 'Visualize, filter, and chart JSON and CSV datasets dynamically.',
    category: 'Data',
    path: '/data-visualizer',
    icon: BarChart2,
  },
];
