import { lazy } from 'react';
import { 
  FileJson, 
  Key, 
  Type, 
  Hash, 
  QrCode, 
  Clock, 
  Ruler, 
  Activity, 
  Palette, 
  Database,
  FileText,
  Link2,
  ImagePlay,
  Files,
  FileDown,
  FileDiff,
  Minimize2,
  BarChart2
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type IOType = 'text' | 'json' | 'csv' | 'url' | 'image' | 'number' | 'pdf' | 'word';

export interface RegistryTool {
  id: string;
  name: string;
  description: string;
  path: string;
  category: string;
  tags: string[];
  inputType: IOType[];
  outputType: IOType[];
  icon: LucideIcon;
  component: React.LazyExoticComponent<any>;
}

export const toolRegistry: RegistryTool[] = [
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and minify JSON data instantly with deep tree view.',
    path: 'json-formatter',
    category: 'Data',
    tags: ['json', 'format', 'dev', 'data'],
    inputType: ['json', 'text'],
    outputType: ['json', 'text'],
    icon: FileJson,
    component: lazy(() => import('./json-formatter')),
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure, complex passwords locally with strength indicator.',
    path: 'password-generator',
    category: 'Security',
    tags: ['password', 'security', 'generator'],
    inputType: [],
    outputType: ['text'],
    icon: Key,
    component: lazy(() => import('./password-generator')),
  },
  {
    id: 'text-to-slug',
    name: 'Text to Slug',
    description: 'Convert any string into a URL-friendly slug.',
    path: 'text-to-slug',
    category: 'String',
    tags: ['text', 'slug', 'url'],
    inputType: ['text'],
    outputType: ['text'],
    icon: Type,
    component: lazy(() => import('./text-to-slug')),
  },
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder/Decoder',
    description: 'Instantly encode or decode Base64 strings safely inside your browser.',
    path: 'base64-encoder',
    category: 'Data',
    tags: ['base64', 'encode', 'decode'],
    inputType: ['text'],
    outputType: ['text'],
    icon: Hash,
    component: lazy(() => import('./base64-encoder')),
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Create and download customizable QR codes for links or text.',
    path: 'qr-generator',
    category: 'Media',
    tags: ['qr', 'code', 'generator'],
    inputType: ['text', 'url'],
    outputType: ['image'],
    icon: QrCode,
    component: lazy(() => import('./qr-generator')),
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps to human-readable dates and vice versa.',
    path: 'timestamp-converter',
    category: 'Time',
    tags: ['time', 'date', 'timestamp'],
    inputType: ['number', 'text'],
    outputType: ['text'],
    icon: Clock,
    component: lazy(() => import('./timestamp-converter')),
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Quickly convert between different units (e.g., kg to block/pound).',
    path: 'unit-converter',
    category: 'Math',
    tags: ['unit', 'convert', 'measure'],
    inputType: ['number'],
    outputType: ['number'],
    icon: Ruler,
    component: lazy(() => import('./unit-converter')),
  },
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate your Body Mass Index based on height and weight.',
    path: 'bmi-calculator',
    category: 'Health',
    tags: ['bmi', 'health', 'fitness'],
    inputType: ['number'],
    outputType: ['number'],
    icon: Activity,
    component: lazy(() => import('./bmi-calculator')),
  },
  {
    id: 'color-palette',
    name: 'Color Palette',
    description: 'Generate beautiful, harmonic color palettes for your next UI.',
    path: 'color-palette',
    category: 'Design',
    tags: ['color', 'palette', 'design'],
    inputType: [],
    outputType: ['text'],
    icon: Palette,
    component: lazy(() => import('./color-palette')),
  },
  {
    id: 'random-data',
    name: 'Random Data Generator',
    description: 'Generate mock user data like names, emails, UUIDs instantly.',
    path: 'random-data',
    category: 'Data',
    tags: ['random', 'data', 'mock', 'json'],
    inputType: [],
    outputType: ['json', 'csv'],
    icon: Database,
    component: lazy(() => import('./random-data')),
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Instantly generate MD5, SHA-1, and SHA-256 hashes online.',
    path: 'hash-generator',
    category: 'Security',
    tags: ['hash', 'md5', 'sha', 'security'],
    inputType: ['text'],
    outputType: ['text'],
    icon: Hash,
    component: lazy(() => import('./hash-generator')),
  },
  {
    id: 'text-case-converter',
    name: 'Text Case Converter',
    description: 'Change text to UPPERCASE, lowercase, camelCase, snake_case.',
    path: 'text-case-converter',
    category: 'String',
    tags: ['text', 'case', 'camelcase'],
    inputType: ['text'],
    outputType: ['text'],
    icon: Type,
    component: lazy(() => import('./text-case-converter')),
  },
  {
    id: 'word-counter',
    name: 'Word & Character Counter',
    description: 'Count words, characters, sentences, and paragraphs instantly.',
    path: 'word-counter',
    category: 'Writing',
    tags: ['word', 'count', 'text'],
    inputType: ['text'],
    outputType: ['number'],
    icon: FileText,
    component: lazy(() => import('./word-counter')),
  },
  {
    id: 'tinyurl-generator',
    name: 'TinyURL Generator',
    description: 'Generate short, readable URLs for long links instantly within your browser.',
    path: 'tinyurl-generator',
    category: 'Network',
    tags: ['url', 'shortener', 'link'],
    inputType: ['url'],
    outputType: ['url'],
    icon: Link2,
    component: lazy(() => import('./tinyurl-generator')),
  },
  {
    id: 'image-to-gif',
    name: 'Images to GIF Converter',
    description: 'Convert multiple images into an animated GIF on the client side.',
    path: 'image-to-gif',
    category: 'Media',
    tags: ['image', 'gif', 'convert'],
    inputType: ['image'],
    outputType: ['image'],
    icon: ImagePlay,
    component: lazy(() => import('./image-to-gif')),
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF Online',
    description: 'Combine multiple PDF documents into one single PDF securely.',
    path: 'merge-pdf',
    category: 'Document',
    tags: ['pdf', 'merge', 'document'],
    inputType: ['pdf'],
    outputType: ['pdf'],
    icon: Files,
    component: lazy(() => import('./merge-pdf')),
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF Converter',
    description: 'Convert .doc and .docx files to PDF instantly and securely.',
    path: 'word-to-pdf',
    category: 'Document',
    tags: ['word', 'pdf', 'convert'],
    inputType: ['word'],
    outputType: ['pdf'],
    icon: FileDown,
    component: lazy(() => import('./word-to-pdf')),
  },
  {
    id: 'diff-checker',
    name: 'Diff Checker',
    description: 'Compare text and JSON differences with side-by-side or inline view.',
    path: 'diff-checker',
    category: 'Developer',
    tags: ['diff', 'compare', 'text', 'json'],
    inputType: ['text', 'json'],
    outputType: ['text', 'json'],
    icon: FileDiff,
    component: lazy(() => import('./diff-checker')),
  },
  {
    id: 'compression-tool',
    name: 'Compression Tool',
    description: 'Gzip compress and decompress text or JSON payloads instantly.',
    path: 'compression-tool',
    category: 'Data',
    tags: ['compress', 'gzip', 'data'],
    inputType: ['text', 'json'],
    outputType: ['text', 'json'],
    icon: Minimize2,
    component: lazy(() => import('./compression-tool')),
  },
  {
    id: 'data-visualizer',
    name: 'Data Visualizer',
    description: 'Visualize, filter, and chart JSON and CSV datasets dynamically.',
    path: 'data-visualizer',
    category: 'Data',
    tags: ['data', 'chart', 'visualize', 'json', 'csv'],
    inputType: ['json', 'csv'],
    outputType: ['image'],
    icon: BarChart2,
    component: lazy(() => import('./data-visualizer')),
  },
];
