import { lazy } from 'react';
import { 
  FileJson, 
  Key, 
  Type, 
  Hash, 
  QrCode, 
  Clock, 
  Ruler, 
  Activity, 
  Palette, 
  Database,
  FileText,
  Link2,
  ImagePlay,
  Files,
  FileDown,
  FileDiff,
  Minimize2,
  BarChart2,
  Workflow,
  ScanLine,
  Wand2,
  Grid3x3,
  Shapes,
  Sparkles,
  Archive,
  LinkIcon,
  Unlink,
  Eraser
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

// Light tools static imports (fast load - main bundle)
import JsonFormatter from './json-formatter';
import PasswordGenerator from './password-generator';
import TextToSlug from './text-to-slug';
import Base64Encoder from './base64-encoder';
import TimestampConverter from './timestamp-converter';
import UnitConverter from './unit-converter';
import BmiCalculator from './bmi-calculator';
import ColorPalette from './color-palette';
import RandomData from './random-data';
import HashGenerator from './hash-generator';
import TextCaseConverter from './text-case-converter';
import WordCounter from './word-counter';
import TinyurlGenerator from './tinyurl-generator';

export type IOType = 'text' | 'json' | 'csv' | 'url' | 'image' | 'number' | 'pdf' | 'word' | 'any';

export interface RegistryTool {
  id: string;
  name: string;
  description: string;
  path: string;
  category: string;
  tags: string[];
  inputType: IOType[];
  outputType: IOType[];
  icon: LucideIcon;
  type: 'light' | 'heavy';
  component: React.ComponentType<any> | React.LazyExoticComponent<any>;
}

export const toolRegistry: RegistryTool[] = [
  {
    id: 'pipeline-builder',
    name: 'Pipeline Builder',
    description: 'Visually connect tools to form a powerful data processing pipeline.',
    path: 'pipeline-builder',
    category: 'Developer',
    tags: ['pipeline', 'workflow', 'chain'],
    inputType: ['any'],
    outputType: ['any'],
    icon: Workflow,
    type: 'heavy',
    component: lazy(() => import('../features/pipeline')),
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and minify JSON data instantly with deep tree view.',
    path: 'json-formatter',
    category: 'Data',
    tags: ['json', 'format', 'dev', 'data'],
    inputType: ['json', 'text'],
    outputType: ['json', 'text'],
    icon: FileJson,
    type: 'light',
    component: JsonFormatter,
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure, complex passwords locally with strength indicator.',
    path: 'password-generator',
    category: 'Security',
    tags: ['password', 'security', 'generator'],
    inputType: [],
    outputType: ['text'],
    icon: Key,
    type: 'light',
    component: PasswordGenerator,
  },
  {
    id: 'text-to-slug',
    name: 'Text to Slug',
    description: 'Convert any string into a URL-friendly slug.',
    path: 'text-to-slug',
    category: 'String',
    tags: ['text', 'slug', 'url'],
    inputType: ['text'],
    outputType: ['text'],
    icon: Type,
    type: 'light',
    component: TextToSlug,
  },
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder/Decoder',
    description: 'Instantly encode or decode Base64 strings safely inside your browser.',
    path: 'base64-encoder',
    category: 'Data',
    tags: ['base64', 'encode', 'decode'],
    inputType: ['text'],
    outputType: ['text'],
    icon: Hash,
    type: 'light',
    component: Base64Encoder,
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Create and download customizable QR codes for links or text.',
    path: 'qr-generator',
    category: 'Media',
    tags: ['qr', 'code', 'generator'],
    inputType: ['text', 'url'],
    outputType: ['image'],
    icon: QrCode,
    type: 'heavy',
    component: lazy(() => import('./qr-generator')),
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps to human-readable dates and vice versa.',
    path: 'timestamp-converter',
    category: 'Time',
    tags: ['time', 'date', 'timestamp'],
    inputType: ['number', 'text'],
    outputType: ['text'],
    icon: Clock,
    type: 'light',
    component: TimestampConverter,
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Quickly convert between different units (e.g., kg to block/pound).',
    path: 'unit-converter',
    category: 'Math',
    tags: ['unit', 'convert', 'measure'],
    inputType: ['number'],
    outputType: ['number'],
    icon: Ruler,
    type: 'light',
    component: UnitConverter,
  },
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate your Body Mass Index based on height and weight.',
    path: 'bmi-calculator',
    category: 'Health',
    tags: ['bmi', 'health', 'fitness'],
    inputType: ['number'],
    outputType: ['number'],
    icon: Activity,
    type: 'light',
    component: BmiCalculator,
  },
  {
    id: 'color-palette',
    name: 'Color Palette',
    description: 'Generate beautiful, harmonic color palettes for your next UI.',
    path: 'color-palette',
    category: 'Design',
    tags: ['color', 'palette', 'design'],
    inputType: [],
    outputType: ['text'],
    icon: Palette,
    type: 'light',
    component: ColorPalette,
  },
  {
    id: 'random-data',
    name: 'Random Data Generator',
    description: 'Generate mock user data like names, emails, UUIDs instantly.',
    path: 'random-data',
    category: 'Data',
    tags: ['random', 'data', 'mock', 'json'],
    inputType: [],
    outputType: ['json', 'csv'],
    icon: Database,
    type: 'light',
    component: RandomData,
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Instantly generate MD5, SHA-1, and SHA-256 hashes online.',
    path: 'hash-generator',
    category: 'Security',
    tags: ['hash', 'md5', 'sha', 'security'],
    inputType: ['text'],
    outputType: ['text'],
    icon: Hash,
    type: 'light',
    component: HashGenerator,
  },
  {
    id: 'text-case-converter',
    name: 'Text Case Converter',
    description: 'Change text to UPPERCASE, lowercase, camelCase, snake_case.',
    path: 'text-case-converter',
    category: 'String',
    tags: ['text', 'case', 'camelcase'],
    inputType: ['text'],
    outputType: ['text'],
    icon: Type,
    type: 'light',
    component: TextCaseConverter,
  },
  {
    id: 'word-counter',
    name: 'Word & Character Counter',
    description: 'Count words, characters, sentences, and paragraphs instantly.',
    path: 'word-counter',
    category: 'Writing',
    tags: ['word', 'count', 'text'],
    inputType: ['text'],
    outputType: ['number'],
    icon: FileText,
    type: 'light',
    component: WordCounter,
  },
  {
    id: 'tinyurl-generator',
    name: 'TinyURL Generator',
    description: 'Generate short, readable URLs for long links instantly within your browser.',
    path: 'tinyurl-generator',
    category: 'Network',
    tags: ['url', 'shortener', 'link'],
    inputType: ['url'],
    outputType: ['url'],
    icon: Link2,
    type: 'light',
    component: TinyurlGenerator,
  },
  {
    id: 'image-to-gif',
    name: 'Images to GIF Converter',
    description: 'Convert multiple images into an animated GIF on the client side.',
    path: 'image-to-gif',
    category: 'Media',
    tags: ['image', 'gif', 'convert'],
    inputType: ['image'],
    outputType: ['image'],
    icon: ImagePlay,
    type: 'heavy',
    component: lazy(() => import('./image-to-gif')),
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF Online',
    description: 'Combine multiple PDF documents into one single PDF securely.',
    path: 'merge-pdf',
    category: 'Document',
    tags: ['pdf', 'merge', 'document'],
    inputType: ['pdf'],
    outputType: ['pdf'],
    icon: Files,
    type: 'heavy',
    component: lazy(() => import('./merge-pdf')),
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF Converter',
    description: 'Convert .doc and .docx files to PDF instantly and securely.',
    path: 'word-to-pdf',
    category: 'Document',
    tags: ['word', 'pdf', 'convert'],
    inputType: ['word'],
    outputType: ['pdf'],
    icon: FileDown,
    type: 'heavy',
    component: lazy(() => import('./word-to-pdf')),
  },
  {
    id: 'diff-checker',
    name: 'Diff Checker',
    description: 'Compare text and JSON differences with side-by-side or inline view.',
    path: 'diff-checker',
    category: 'Developer',
    tags: ['diff', 'compare', 'text', 'json'],
    inputType: ['text', 'json'],
    outputType: ['text', 'json'],
    icon: FileDiff,
    type: 'heavy',
    component: lazy(() => import('./diff-checker')),
  },
  {
    id: 'compression-tool',
    name: 'Compression Tool',
    description: 'Gzip compress and decompress text or JSON payloads instantly.',
    path: 'compression-tool',
    category: 'Data',
    tags: ['compress', 'gzip', 'data'],
    inputType: ['text', 'json'],
    outputType: ['text', 'json'],
    icon: Minimize2,
    type: 'heavy',
    component: lazy(() => import('./compression-tool')),
  },
  {
    id: 'data-visualizer',
    name: 'Data Visualizer',
    description: 'Visualize, filter, and chart JSON and CSV datasets dynamically.',
    path: 'data-visualizer',
    category: 'Data',
    tags: ['data', 'chart', 'visualize', 'json', 'csv'],
    inputType: ['json', 'csv'],
    outputType: ['image'],
    icon: BarChart2,
    type: 'heavy',
    component: lazy(() => import('./data-visualizer')),
  },
  // ── Creative Design Tools ───────────────────────────────────────────────────
  {
    id: 'svg-tracer',
    name: 'SVG Tracer',
    description: 'Convert PNG/JPG images into scalable SVG vector files with color depth and detail controls.',
    path: 'svg-tracer',
    category: 'Creative',
    tags: ['svg', 'vector', 'image', 'trace', 'figma'],
    inputType: ['image'],
    outputType: ['image'],
    icon: ScanLine,
    type: 'heavy',
    component: lazy(() => import('./svg-tracer')),
  },
  {
    id: 'image-filter',
    name: 'Image Filter',
    description: 'Apply halftone, dither, neon glow, pixelate, posterize and more to any image in-browser.',
    path: 'image-filter',
    category: 'Creative',
    tags: ['filter', 'halftone', 'dither', 'image', 'effects'],
    inputType: ['image'],
    outputType: ['image'],
    icon: Wand2,
    type: 'heavy',
    component: lazy(() => import('./image-filter')),
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art Generator',
    description: 'Convert photos into retro pixel art with Game Boy, NES, C64 and custom palettes.',
    path: 'pixel-art',
    category: 'Creative',
    tags: ['pixel', 'retro', 'art', 'image', 'gameboy', 'nes'],
    inputType: ['image'],
    outputType: ['image'],
    icon: Grid3x3,
    type: 'heavy',
    component: lazy(() => import('./pixel-art')),
  },
  {
    id: 'pattern-generator',
    name: 'Pattern Generator',
    description: 'Create beautiful geometric patterns — hexagons, waves, diamonds and more. Export as PNG or SVG.',
    path: 'pattern-generator',
    category: 'Creative',
    tags: ['pattern', 'geometric', 'svg', 'design', 'background'],
    inputType: ['any'],
    outputType: ['image'],
    icon: Shapes,
    type: 'heavy',
    component: lazy(() => import('./pattern-generator')),
  },
  {
    id: 'text-particle',
    name: 'Text Particle Effect',
    description: 'Animated particle text — watch any word explode into dots and reassemble in real-time.',
    path: 'text-particle',
    category: 'Creative',
    tags: ['particle', 'animation', 'canvas', 'text', 'effect'],
    inputType: ['text'],
    outputType: ['image'],
    icon: Sparkles,
    type: 'heavy',
    component: lazy(() => import('./text-particle')),
  },
  {
    id: 'geo-art',
    name: 'Geo Art Generator',
    description: 'Fill a 2×2 to 5×5 grid with random geometric shapes and export stunning abstract art as SVG or PNG.',
    path: 'geo-art',
    category: 'Creative',
    tags: ['geo', 'geometric', 'art', 'grid', 'abstract', 'svg', 'design'],
    inputType: ['any'],
    outputType: ['image'],
    icon: Shapes,
    type: 'heavy',
    component: lazy(() => import('./geo-art')),
  },
  {
    id: 'text-background',
    name: 'Text Background Generator',
    description: 'Create premium tilted repeating text backgrounds with custom fonts, colors, tilt and mask shapes. Export as PNG or SVG.',
    path: 'text-background',
    category: 'Creative',
    tags: ['text', 'background', 'pattern', 'font', 'design', 'website'],
    inputType: ['text'],
    outputType: ['image'],
    icon: Type,
    type: 'heavy',
    component: lazy(() => import('./text-background')),
  },
  {
    id: 'live-particles',
    name: 'Live Particle Canvas',
    description: 'Interactive particle animations with 8 flow patterns — flower, vortex, starfield, text and more. Hover to interact, record as video, export as PNG.',
    path: 'live-particles',
    category: 'Creative',
    tags: ['particle', 'animation', 'canvas', 'interactive', 'live', 'record', 'pattern'],
    inputType: ['any'],
    outputType: ['image'],
    icon: Sparkles,
    type: 'heavy',
    component: lazy(() => import('./live-particles')),
  },
  {
    id: 'remove-background',
    name: 'Remove Background',
    description: 'Remove image backgrounds by selecting a color. Click on background and adjust sensitivity for precise results.',
    path: 'remove-background',
    category: 'Creative',
    tags: ['background', 'remove', 'transparency', 'image', 'editing'],
    inputType: ['image'],
    outputType: ['image'],
    icon: Eraser,
    type: 'heavy',
    component: lazy(() => import('./remove-background')),
  },
  // ── Pipeline-only Nodes ─────────────────────────────────────────────────────
  {
    id: 'tinyurl-shorten',
    name: 'TinyURL Shorten',
    description: 'Shorten one or more URLs using the TinyURL API. Pass newline-separated URLs as input.',
    path: 'pipeline-builder',
    category: 'Network',
    tags: ['url', 'shorten', 'tinyurl', 'pipeline'],
    inputType: ['url', 'text'],
    outputType: ['url'],
    icon: LinkIcon,
    type: 'heavy',
    component: lazy(() => import('../features/pipeline')),
  },
  {
    id: 'tinyurl-expand',
    name: 'TinyURL Expand',
    description: 'Resolve short URLs back to their original form. Works like a cURL HEAD request.',
    path: 'pipeline-builder',
    category: 'Network',
    tags: ['url', 'expand', 'resolve', 'curl', 'pipeline'],
    inputType: ['url', 'text'],
    outputType: ['url'],
    icon: Unlink,
    type: 'heavy',
    component: lazy(() => import('../features/pipeline')),
  },
  {
    id: 'download-zip',
    name: 'Download ZIP',
    description: 'Bundle pipeline output into a compressed ZIP file. Supports Deflate (zlib) or no compression.',
    path: 'pipeline-builder',
    category: 'Data',
    tags: ['zip', 'compress', 'download', 'deflate', 'pipeline'],
    inputType: ['any'],
    outputType: ['any'],
    icon: Archive,
    type: 'heavy',
    component: lazy(() => import('../features/pipeline')),
  },
];
